spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/resolar
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: resolar
    password: resolar123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

ai:
  service:
    url: https://d0286425ad20.ngrok-free.app